# Generated by Django 4.2.2 on 2023-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansforgood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproposal',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
