# Generated by Django 4.2.2 on 2023-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansforgood', '0002_loanproposal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproposal',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
